[package]
name = "teams_status"
version = "0.4.1"
edition = "2021"

[package.metadata.winres]
ProductName = "Teams Status"
ProductVersion = "0.4.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home-assistant-rest = "0.2.0"
actix-rt = "2.9.0"
log = "0.4.21"
chrono = "0.4.37"
tokio-tungstenite = "0.21.0"
url = "2.5.0"
json = "0.12.4"
tokio = { version = "1.37", features = ["full"] }
tray-item = "0.10.0"
futures-util = "0.3.30"
futures-channel = "0.3.30"
log4rs = "1.3.0"
rust-ini = "0.21.0"
magic-crypt = "3.1.13"
rumqttc = "0.24.0"
serde_json = "1.0.115"
async-trait = "0.1.79"
anyhow = "1.0.82"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
# regex = "1.10.3" # for teams_log
# notify = { version = "6.1.1" } # for teams_log

[build-dependencies]
winres = "0.1.12"
