[package]
name = "teams_status"
version = "1.0.0"
edition = "2021"

[package.metadata.winres]
ProductName = "Teams Status"
ProductVersion = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# temporary until the following crate is updated with the new fixes
home-assistant-rest = { path = "./../home-assistant-rest" }
actix-rt = "2.10.0"
log = "0.4.22"
chrono = "0.4.38"
tokio-tungstenite = "0.22.0" # 0.23 has a breaking change, will need to review when upgrading
url = "2.5.2"
json = "0.12.4"
tokio = { version = "1.38.0", features = ["full"] }
tray-item = "0.10.0"
futures-util = "0.3.30"
futures-channel = "0.3.30"
log4rs = "1.3.0"
rust-ini = "0.21.0"
magic-crypt = "3.1.13"
rumqttc = "0.24.0"
serde_json = "1.0.119"
async-trait = "0.1.80"
anyhow = "1.0.86"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
# regex = "1.10.3" # for teams_log
# notify = { version = "6.1.1" } # for teams_log

[build-dependencies]
winres = "0.1.12"
