[package]
name = "teams_status"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "*"
home-assistant-rest = "*"
actix-rt = "*"
log = "*"
chrono = "*"
tungstenite = "*"
url = "*"
json = "*"
tokio = { version = "*", features = ["full"] }