[package]
name = "teams_status"
version = "0.2.1"
edition = "2021"

[package.metadata.winres]
ProductName = "Teams Status"
ProductVersion = "0.2.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home-assistant-rest = "0.2.0"
actix-rt = "2.9.0"
log = "0.4.20"
chrono = "0.4.31"
tokio-tungstenite = "0.20.1"
url = "2.4.1"
json = "0.12.4"
tokio = { version = "1.34.0", features = ["full"] }
tray-item = "0.9.0"
futures-util = "0.3.29"
futures-channel = "0.3.29"
log4rs = "1.2.0"
rust-ini = "0.20.0"
magic-crypt = "3.1.13"
rumqttc = "0.23.0"
serde_json = "1.0.108"
async-trait = "0.1.74"

[build-dependencies]
winres = "0.1.12"
