[package]
name = "teams_status"
version = "0.3.0"
edition = "2021"

[package.metadata.winres]
ProductName = "Teams Status"
ProductVersion = "0.3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home-assistant-rest = "0.2.0"
actix-rt = "2.9.0"
log = "0.4.21"
chrono = "0.4.35"
tokio-tungstenite = "0.21.0"
url = "2.5.0"
json = "0.12.4"
tokio = { version = "1.36", features = ["full"] }
tray-item = "0.9.0"
futures-util = "0.3.30"
futures-channel = "0.3.30"
log4rs = "1.3.0"
rust-ini = "0.21.0"
magic-crypt = "3.1.13"
rumqttc = "0.24.0"
serde_json = "1.0.114"
async-trait = "0.1.77"
anyhow = "1.0.81"

[build-dependencies]
winres = "0.1.12"

[profile.release-unoptimized]
inherits = "release"
opt-level = 0
