[package]
name = "teams_status"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "*"
home-assistant-rest = "*" # Might need to run "sudo apt install openssl-dev" and maybe for pkg-config
actix-rt = "*"
log = "*"
chrono = "*"